title: RedClaw Technologies
tagline: Real-time, High Concurrency, and IoT Software Consultancy
url: https://www.redcalwtech.com/
lang: en_US
description: Hire us to develop your real-time, high concurrency web systems or IoT infrastructures. We are experts in Erlang/OTP, Elixir and MQTT."
email: info [at] redclawtech [dot] com
email-hidden: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;%69%6E%66%6F%40%72%65%64%63%6C%61%77%74%65%63%68%2E%63%6F%6D"
phone: +1-727-488-9109
address: Largo, Florida
github: https://github.com/redclawtech
linkedin: https://www.linkedin.com/company/redclawtech/
twitter:
  username: RedClawTech
footer: RedClaw Technologies LLC.

plugins:
  - jekyll-seo-tag

exclude:
  - vendor/bundle
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - CNAME
