title: RedClaw Technologies
email: info [at] redclawtech [dot] com
email-hidden: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;%69%6E%66%6F%40%72%65%64%63%6C%61%77%74%65%63%68%2E%63%6F%6D"
phone: +1-727-488-9109
address: Largo, Florida
github: https://github.com/redclawtech
linkedin: https://www.linkedin.com/company/redclawtech/
twitter: https://twitter.com/RedClawTech
footer: RedClaw Technologies LLC.

exclude:
# For building on TravisCI.
# See: https://jekyllrb.com/docs/continuous-integration/travis-ci/
- vendor/bundle
- node_modules/
